import type { IncomingMessage, ServerResponse } from 'http';
import fs from 'fs';
import path from 'path';

// Server-side secret token storage path (never committed to git)
const TOKEN_FILE_PATH = path.resolve(process.cwd(), '.telegram_token');

// In-memory publication cache to prevent duplicate broadcasts within a 5-minute window
interface RecentPublication {
  timestamp: number;
  messageId?: number | string;
}
const recentPublications = new Map<string, RecentPublication>();

/**
 * Safely sanitizes any error message or string so Bot Tokens are NEVER leaked
 * even if Node fetch or curl includes the full URL in the exception message.
 */
export function sanitizeTelegramString(text: string, token?: string): string {
  if (!text) return '';
  let sanitized = text;
  if (token && token.length > 5) {
    sanitized = sanitized.split(token).join('[REDACTED_BOT_TOKEN]');
  }
  // Generic token pattern matching (e.g. 123456789:ABCdefGhIjkLmNoPqRsTuVwXyZ)
  sanitized = sanitized.replace(/bot\d+:[a-zA-Z0-9_-]+/gi, 'bot[REDACTED_TOKEN]');
  return sanitized;
}

/**
 * Normalizes Telegram Channel ID to ensure proper -100 prefix for channels/supergroups
 */
export function normalizeChannelId(raw: string): string {
  const clean = (raw || '').trim();
  if (!clean) return '-1003328935535';
  if (clean.startsWith('@')) return clean;
  // If purely numeric without minus
  if (/^\d+$/.test(clean)) {
    if (clean.startsWith('100')) return `-${clean}`;
    return `-100${clean}`;
  }
  // If starts with single minus but missing 100
  if (clean.startsWith('-') && !clean.startsWith('-100') && /^\-\d+$/.test(clean)) {
    return `-100${clean.slice(1)}`;
  }
  return clean;
}

/**
 * Translates raw Telegram API error descriptions into clear, actionable admin guidance
 */
function translateTelegramError(desc: string): string {
  const d = (desc || '').toLowerCase();
  if (d.includes('chat not found')) {
    return 'Target Telegram Channel was not found. Please verify the Channel ID (e.g., -1003328935535) and verify the channel exists.';
  }
  if (d.includes('bot was kicked') || d.includes('not a member')) {
    return 'The Telegram Bot is not a member of the target channel. Please add your Bot as an Administrator to the channel.';
  }
  if (d.includes('not enough rights') || d.includes('need administrator rights') || d.includes('cannot post')) {
    return 'The Telegram Bot is in the channel but lacks Administrator rights to "Post Messages". Please edit Admin permissions in Telegram Channel Settings.';
  }
  if (d.includes('unauthorized') || d.includes('token is invalid') || d.includes('wrong bot token')) {
    return 'Invalid Telegram Bot Token. Please check and re-enter the token generated by @BotFather.';
  }
  if (d.includes('too many requests') || d.includes('retry after')) {
    return 'Telegram API rate limit reached. The request has been throttled; please wait a moment before trying again.';
  }
  if (d.includes('message is too long')) {
    return 'The broadcast message exceeds Telegram character limits (4096 characters). Content was truncated.';
  }
  return desc || 'Telegram API request failed.';
}

/**
 * Safely retrieves server-side bot token.
 * Precedence: process.env.TELEGRAM_BOT_TOKEN -> .telegram_token file
 */
export function getServerTelegramToken(): string {
  if (process.env.TELEGRAM_BOT_TOKEN && process.env.TELEGRAM_BOT_TOKEN !== 'YOUR_TELEGRAM_BOT_TOKEN') {
    return process.env.TELEGRAM_BOT_TOKEN.trim();
  }
  try {
    if (fs.existsSync(TOKEN_FILE_PATH)) {
      const stored = fs.readFileSync(TOKEN_FILE_PATH, 'utf-8').trim();
      if (stored) return stored;
    }
  } catch (e) {}
  return '';
}

/**
 * Stores updated bot token securely on server side
 */
export function setServerTelegramToken(token: string): boolean {
  try {
    fs.writeFileSync(TOKEN_FILE_PATH, token.trim(), { mode: 0o600 });
    return true;
  } catch (e) {
    return false;
  }
}

/**
 * Calls Telegram Bot API with automatic token redaction and retry handling
 */
async function callTelegramApi(
  endpoint: string,
  payload: Record<string, any>,
  tokenOverride?: string,
  maxRetries = 2
) {
  const token = tokenOverride || getServerTelegramToken();
  if (!token) {
    throw new Error('Telegram Bot Token is not configured on the server. Please enter token in Admin Settings.');
  }

  const url = `https://api.telegram.org/bot${token}/${endpoint}`;
  let lastError: any = null;

  for (let attempt = 1; attempt <= maxRetries; attempt++) {
    try {
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 12000);

      const response = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
        signal: controller.signal,
      });

      clearTimeout(timeoutId);

      const data = (await response.json()) as any;
      if (!data.ok) {
        const errorDesc = translateTelegramError(data.description || '');
        throw new Error(errorDesc);
      }
      return data.result;
    } catch (err: any) {
      lastError = err;
      // Sanitize token immediately from error message
      const sanitized = sanitizeTelegramString(err.message || 'Telegram network request failed', token);
      err.message = sanitized;

      // Do not retry on client/auth errors (401, 403, 400)
      if (
        sanitized.includes('Invalid Telegram Bot Token') ||
        sanitized.includes('not found') ||
        sanitized.includes('Administrator')
      ) {
        throw new Error(sanitized);
      }

      // If transient failure, wait briefly before retrying
      if (attempt < maxRetries) {
        await new Promise((resolve) => setTimeout(resolve, 1000 * attempt));
      }
    }
  }

  const finalMsg = sanitizeTelegramString(lastError?.message || 'Telegram API request failed after retries', token);
  throw new Error(finalMsg);
}

/**
 * Helper to parse JSON body from incoming HTTP request
 */
function parseBody(req: IncomingMessage): Promise<any> {
  return new Promise((resolve, reject) => {
    let body = '';
    req.on('data', (chunk) => (body += chunk));
    req.on('end', () => {
      try {
        resolve(body ? JSON.parse(body) : {});
      } catch (err) {
        reject(err);
      }
    });
    req.on('error', reject);
  });
}

/**
 * Middleware handling /api/telegram/* requests
 */
export async function handleTelegramRequest(req: IncomingMessage, res: ServerResponse): Promise<boolean> {
  const rawUrl = req.url || '';
  if (!rawUrl.startsWith('/api/telegram/')) {
    return false;
  }

  // Strip query parameters for accurate routing
  const pathname = rawUrl.split('?')[0];
  res.setHeader('Content-Type', 'application/json');

  try {
    // 1. GET /api/telegram/status
    if (pathname === '/api/telegram/status' && req.method === 'GET') {
      const token = getServerTelegramToken();
      const hasToken = Boolean(token && token.length > 5);
      let botUsername = '';

      if (hasToken) {
        try {
          const me = await callTelegramApi('getMe', {}, token, 1);
          botUsername = me.username || '';
        } catch (e) {
          // Token exists but failed verification
        }
      }

      res.end(
        JSON.stringify({
          hasTokenConfigured: hasToken,
          channelId: '-1003328935535',
          botUsername,
        })
      );
      return true;
    }

    // 2. POST /api/telegram/save-token
    if (pathname === '/api/telegram/save-token' && req.method === 'POST') {
      const body = await parseBody(req);
      const token = body.token?.trim();
      if (token) {
        setServerTelegramToken(token);
        // Verify token with getMe
        try {
          const me = await callTelegramApi('getMe', {}, token, 1);
          res.end(
            JSON.stringify({
              success: true,
              message: `Bot token verified! Connected as @${me.username}`,
              botUsername: me.username,
            })
          );
          return true;
        } catch (err: any) {
          res.end(
            JSON.stringify({
              success: false,
              error: `Invalid Bot Token: ${sanitizeTelegramString(err.message, token)}`,
            })
          );
          return true;
        }
      }
      res.end(JSON.stringify({ success: false, error: 'Empty token provided.' }));
      return true;
    }

    // 3. POST /api/telegram/test-connection
    if (pathname === '/api/telegram/test-connection' && req.method === 'POST') {
      try {
        const me = await callTelegramApi('getMe', {});
        res.end(
          JSON.stringify({
            success: true,
            botUsername: me.username,
            firstName: me.first_name,
            message: `Bot @${me.username} is online and operational.`,
          })
        );
      } catch (err: any) {
        res.end(JSON.stringify({ success: false, error: sanitizeTelegramString(err.message) }));
      }
      return true;
    }

    // 4. POST /api/telegram/send-test
    if (pathname === '/api/telegram/send-test' && req.method === 'POST') {
      const body = await parseBody(req);
      const targetChannel = normalizeChannelId(body.channelId || '-1003328935535');
      const timestamp = new Date().toLocaleString('en-US', { timeZone: 'Asia/Karachi' });

      const text =
        `📢 <b>SargodhaMart Telegram Automation Test</b>\n\n` +
        `✅ <b>Status:</b> Telegram Bot integration is successfully connected and operational!\n` +
        `📍 <b>Target Channel:</b> <code>${targetChannel}</code>\n` +
        `🕒 <b>Server Time:</b> ${timestamp}\n\n` +
        `🛍️ <i>Direct trading & verified local employment for Sargodha, Shaheenabad, and Sillanwali.</i>`;

      try {
        const result = await callTelegramApi('sendMessage', {
          chat_id: targetChannel,
          text: text,
          parse_mode: 'HTML',
          reply_markup: {
            inline_keyboard: [
              [
                { text: '🌐 Open SargodhaMart', url: body.websiteUrl || 'https://sargodhamart.com' },
                { text: '💬 WhatsApp Channel', url: 'https://whatsapp.com/channel/0029Vb8bmhAGk1Fzze6iTX0g' },
              ],
            ],
          },
        });

        res.end(
          JSON.stringify({
            success: true,
            messageId: result.message_id,
            message: `Test message successfully delivered to channel ${targetChannel} (Message ID: ${result.message_id})`,
          })
        );
      } catch (err: any) {
        res.end(
          JSON.stringify({
            success: false,
            error: sanitizeTelegramString(err.message) || 'Failed to send message to Telegram channel. Ensure bot is added as Admin in the channel.',
          })
        );
      }
      return true;
    }

    // 5. POST /api/telegram/publish
    if (pathname === '/api/telegram/publish' && req.method === 'POST') {
      const body = await parseBody(req);
      const targetChannel = normalizeChannelId(body.channelId || '-1003328935535');
      const { type, item, websiteUrl, force } = body;

      if (!item) {
        res.end(JSON.stringify({ success: false, error: 'Missing content payload.' }));
        return true;
      }

      // Duplicate prevention: check cache
      const cacheKey = `${type}-${item.id}-${targetChannel}`;
      const now = Date.now();
      const existing = recentPublications.get(cacheKey);
      if (existing && !force && now - existing.timestamp < 180000) {
        res.end(
          JSON.stringify({
            success: true,
            messageId: existing.messageId || 'cached',
            message: `Notice: This ${type} was already published to Telegram channel recently. Duplicate broadcast prevented.`,
            isDuplicate: true,
          })
        );
        return true;
      }

      let messageText = '';
      const inlineKeyboard: Array<Array<{ text: string; url: string }>> = [];

      if (type === 'product') {
        const price = Number(item.price).toLocaleString();
        const locationText = [item.area, item.tehsilName || item.city, item.districtName || 'Sargodha']
          .filter(Boolean)
          .join(', ');

        messageText =
          `🛍️ <b>NEW VERIFIED LISTING ON SARGODHAMART</b>\n\n` +
          `📦 <b>${escapeHtml(item.title)}</b>\n` +
          `💰 <b>Price:</b> Rs. ${price}\n` +
          `📍 <b>Location:</b> ${escapeHtml(locationText)}\n` +
          `🏷️ <b>Condition:</b> ${escapeHtml(item.condition || 'Used')}\n\n` +
          `📝 <i>${escapeHtml((item.description || '').slice(0, 220))}${(item.description || '').length > 220 ? '...' : ''}</i>\n\n` +
          `🛡️ <i>Direct verified seller from Sargodha District</i>`;

        const row1 = [{ text: '🔍 View Product on Website', url: `${websiteUrl || 'https://sargodhamart.com'}/?product=${item.id}` }];
        inlineKeyboard.push(row1);

        const contactRow: Array<{ text: string; url: string }> = [];
        if (item.sellerPhone) {
          contactRow.push({ text: `📞 Call (${item.sellerPhone})`, url: `tel:${item.sellerPhone}` });
        }
        if (item.sellerPhone || item.sellerWhatsappGroup) {
          const rawWa = (item.sellerPhone || '').replace(/\D/g, '');
          const waNum = rawWa.startsWith('0') ? `92${rawWa.slice(1)}` : rawWa;
          contactRow.push({
            text: '💬 WhatsApp',
            url: `https://wa.me/${waNum}?text=${encodeURIComponent(`Salam! Saw your listing "${item.title}" on SargodhaMart.`)}`,
          });
        }
        if (contactRow.length > 0) inlineKeyboard.push(contactRow);
      } else if (type === 'job') {
        const typeLabel = item.postType === 'need_worker' ? '🏢 Employer Hiring' : '👤 Worker Seeking Employment';
        const locationText = [item.area, item.tehsilName || item.city, item.districtName || 'Sargodha']
          .filter(Boolean)
          .join(', ');

        messageText =
          `💼 <b>NEW LOCAL JOB / ROZGAR OPPORTUNITY</b>\n\n` +
          `📌 <b>${escapeHtml(item.title)}</b>\n` +
          `📋 <b>Category:</b> ${escapeHtml(typeLabel)}\n` +
          `📍 <b>Location:</b> ${escapeHtml(locationText)}\n` +
          (item.salaryOrPayment ? `💵 <b>Compensation:</b> ${escapeHtml(item.salaryOrPayment)}\n` : '') +
          `🛠️ <b>Skills:</b> ${escapeHtml(item.skills || 'General')}\n\n` +
          `📝 <i>${escapeHtml((item.description || '').slice(0, 200))}${(item.description || '').length > 200 ? '...' : ''}</i>\n\n` +
          `🛡️ <i>SargodhaMart Local Employment Hub</i>`;

        const row1 = [{ text: '💼 View Job Details', url: `${websiteUrl || 'https://sargodhamart.com'}/?job=${item.id}` }];
        inlineKeyboard.push(row1);

        const contactRow: Array<{ text: string; url: string }> = [];
        if (item.phone) {
          contactRow.push({ text: `📞 Call (${item.phone})`, url: `tel:${item.phone}` });
        }
        if (item.whatsapp || item.phone) {
          const rawWa = (item.whatsapp || item.phone).replace(/\D/g, '');
          const waNum = rawWa.startsWith('0') ? `92${rawWa.slice(1)}` : rawWa;
          contactRow.push({
            text: '💬 WhatsApp',
            url: `https://wa.me/${waNum}?text=${encodeURIComponent(`Salam! Saw your job post "${item.title}" on SargodhaMart.`)}`,
          });
        }
        if (contactRow.length > 0) inlineKeyboard.push(contactRow);
      } else if (type === 'announcement') {
        messageText =
          `📢 <b>OFFICIAL SARGODHAMART ANNOUNCEMENT</b>\n\n` +
          `⭐ <b>${escapeHtml(item.title)}</b>\n\n` +
          `${escapeHtml(item.message)}\n\n` +
          `🌐 <i>SargodhaMart - Buy • Sell • Jobs • Grow</i>`;

        if (item.buttonText && item.buttonUrl) {
          inlineKeyboard.push([{ text: item.buttonText, url: item.buttonUrl }]);
        }
      }

      try {
        const payload: Record<string, any> = {
          chat_id: targetChannel,
          text: messageText,
          parse_mode: 'HTML',
        };
        if (inlineKeyboard.length > 0) {
          payload.reply_markup = { inline_keyboard: inlineKeyboard };
        }

        const result = await callTelegramApi('sendMessage', payload);
        const msgId = result.message_id;

        // Save to cache for duplicate prevention
        recentPublications.set(cacheKey, { timestamp: now, messageId: msgId });

        res.end(
          JSON.stringify({
            success: true,
            messageId: msgId,
            message: `Published to Telegram channel ${targetChannel} (Message ID: ${msgId})`,
          })
        );
      } catch (err: any) {
        res.end(
          JSON.stringify({
            success: false,
            error: sanitizeTelegramString(err.message) || 'Telegram broadcast failed.',
          })
        );
      }
      return true;
    }

    res.statusCode = 404;
    res.end(JSON.stringify({ error: 'Endpoint not found' }));
    return true;
  } catch (err: any) {
    res.statusCode = 500;
    res.end(JSON.stringify({ error: sanitizeTelegramString(err.message) || 'Internal Server Error' }));
    return true;
  }
}

function escapeHtml(text: string): string {
  return (text || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}
